language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_ba292f01bed3_key -iv $encrypted_ba292f01bed3_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_success:
- .travis/deploy.sh
